const createImage = (text, size = '1200x800', bg = 'F6EFE8', fg = '6F4E37') =>
  `https://placehold.co/${size}/${bg}/${fg}.png?text=${encodeURIComponent(text)}`;

const createAvatar = (name, bg = 'EADFD2', fg = '7A5C45') => createImage(name, '320x320', bg, fg);

const IMAGE_SET = {
  bannerWarm: createImage('YIJIANG+Hero+Warm+Commercial', '1440x860', 'F5E9E2', '7D5642'),
  bannerFilm: createImage('YIJIANG+Hero+Film+Emulation', '1440x860', 'EEE7DE', '5F4A3D'),
  bannerWorkflow: createImage('YIJIANG+Hero+Delivery+Workflow', '1440x860', 'F3ECE6', '72503B'),
  bannerPortrait: createImage('YIJIANG+Hero+Portrait+Skin+Tone', '1440x860', 'F8EEE8', '8B5E46'),
  inspirePalette: createImage('Lookbook+Color+Palette', '960x720', 'F3E7DD', '765743'),
  inspireCase: createImage('Commercial+Case+Breakdown', '960x720', 'EFE5DD', '6B4F3D'),
  inspireWorkflow: createImage('ACES+Node+Workflow', '960x720', 'F5ECE5', '715542'),
  inspireReference: createImage('Reference+Frame+Library', '960x720', 'F8EFE7', '7C5D48'),
  articleMonitor: createImage('HDR+Monitoring+Guide', '880x620', 'F4E8DE', '745240'),
  articleSkin: createImage('Skin+Tone+Control+Guide', '880x620', 'F7ECE5', '7A5A45'),
  articleWorkflow: createImage('DaVinci+Workflow+Checklist', '880x620', 'F0E6DE', '69503F'),
  articleDelivery: createImage('Client+Delivery+Template', '880x620', 'F3ECE8', '7A5744'),
};

const PRODUCT_IMAGES = {
  portraitPro: [
    createImage('Portrait+Pro+Cover', '1200x920', 'F9EEE8', '845843'),
    createImage('Portrait+Pro+Look+01', '1200x920', 'F3E4D9', '75513F'),
    createImage('Portrait+Pro+Look+02', '1200x920', 'F7ECE7', '8B614B'),
  ],
  weddingSoft: [
    createImage('Wedding+Soft+Cover', '1200x920', 'FBF0EA', '8A614D'),
    createImage('Wedding+Soft+Look+01', '1200x920', 'F5E8E0', '7A5846'),
    createImage('Wedding+Soft+Look+02', '1200x920', 'F8EEE9', '88644C'),
  ],
  adLux: [
    createImage('Luxury+Commercial+Cover', '1200x920', 'F4E8DE', '6E503E'),
    createImage('Luxury+Commercial+Look+01', '1200x920', 'EEE3DA', '654B3D'),
    createImage('Luxury+Commercial+Look+02', '1200x920', 'F7ECE3', '7C5A47'),
  ],
  foodAd: [
    createImage('Food+Commercial+Cover', '1200x920', 'F6EADF', '815844'),
    createImage('Food+Commercial+Look+01', '1200x920', 'F1E3D6', '72513F'),
    createImage('Food+Commercial+Look+02', '1200x920', 'FAEFE6', '8A624B'),
  ],
  filmDust: [
    createImage('Film+Dust+Cover', '1200x920', 'ECE4DB', '5C4A3D'),
    createImage('Film+Dust+Look+01', '1200x920', 'E8DED4', '554538'),
    createImage('Film+Dust+Look+02', '1200x920', 'F2EAE2', '6A5648'),
  ],
  indieMuted: [
    createImage('Indie+Muted+Cover', '1200x920', 'EFE8E2', '675245'),
    createImage('Indie+Muted+Look+01', '1200x920', 'E9E1D8', '5F4D41'),
    createImage('Indie+Muted+Look+02', '1200x920', 'F5ECE7', '736051'),
  ],
  docNatural: [
    createImage('Documentary+Natural+Cover', '1200x920', 'F5EDE4', '6F5743'),
    createImage('Documentary+Natural+Look+01', '1200x920', 'EEE6DD', '65503F'),
    createImage('Documentary+Natural+Look+02', '1200x920', 'F7EFE9', '79604A'),
  ],
  newsFast: [
    createImage('Fast+Turnaround+Cover', '1200x920', 'F3ECE4', '6C5443'),
    createImage('Fast+Turnaround+Look+01', '1200x920', 'EEE5DB', '604C3E'),
    createImage('Fast+Turnaround+Look+02', '1200x920', 'F8F0E8', '77604C'),
  ],
  nodeMaster: [
    createImage('Node+Master+Cover', '1200x920', 'F1E7DF', '684F40'),
    createImage('Node+Master+Look+01', '1200x920', 'EDE3D9', '5E483A'),
    createImage('Node+Master+Look+02', '1200x920', 'F7EEE6', '7B5E4B'),
  ],
  deliveryPack: [
    createImage('Delivery+Pack+Cover', '1200x920', 'F5EBE3', '6A5241'),
    createImage('Delivery+Pack+Look+01', '1200x920', 'EFE4DA', '614C3D'),
    createImage('Delivery+Pack+Look+02', '1200x920', 'F9EFE7', '7A5F4A'),
  ],
};

export const HOME_MOCK = {
  app: {
    name: '艺匠调色',
    slogan: '电影级调色资产与交付工作流库',
    version: '3.0.0',
  },
  headline: {
    eyebrow: '专业创作者的数字调色资产仓',
    title: '把风格、流程与交付一次做专业',
    subtitle: 'LUT / PowerGrade / ACES / 商业交付模板',
  },
  metrics: [
    { id: 'metric_001', value: '128+', label: '可售数字资产' },
    { id: 'metric_002', value: '32', label: '可复用工作模板' },
    { id: 'metric_003', value: '4.9/5', label: '平均用户评分' },
  ],
  quickEntries: [
    {
      id: 'entry_001',
      title: '本周主推套装',
      subtitle: '商业广告与人像项目高复用方案',
      badge: 'Featured',
      target: 'productSection',
    },
    {
      id: 'entry_002',
      title: '灵感拆解',
      subtitle: '从参考帧到实际节点结构',
      badge: 'Inspiration',
      target: 'inspirationSection',
    },
    {
      id: 'entry_003',
      title: '流程模板',
      subtitle: '从调色到交付的清单化协作',
      badge: 'Workflow',
      target: 'articleSection',
    },
  ],
  banners: [
    {
      id: 'banner_001',
      title: '商业广告主视觉调色套装',
      subtitle: '高对比、干净肤色、产品高光层次一步到位',
      description: '适合品牌 KV、短视频广告、客户提案样片与高频商业交付。',
      image: IMAGE_SET.bannerWarm,
      buttonText: '查看主推',
      badge: 'Featured',
    },
    {
      id: 'banner_002',
      title: '胶片仿真系列上新',
      subtitle: '低饱和、软肩高光与更自然的情绪密度',
      description: '面向剧情短片、婚礼纪录、访谈与品牌故事片的胶片气质资产。',
      image: IMAGE_SET.bannerFilm,
      buttonText: '浏览系列',
      badge: 'New',
    },
    {
      id: 'banner_003',
      title: 'DaVinci 交付流程模板',
      subtitle: '项目命名、节点规范、客户交付一次理顺',
      description: '为个人调色师和小团队准备的标准化流程模板，适合长期复用。',
      image: IMAGE_SET.bannerWorkflow,
      buttonText: '获取模板',
      badge: 'Workflow',
    },
    {
      id: 'banner_004',
      title: '人像肤色控制精选',
      subtitle: '更稳定的肤色、环境色压制和高级感微调',
      description: '适合写真、婚礼、轻商业人像与高客单价形象片的落地项目。',
      image: IMAGE_SET.bannerPortrait,
      buttonText: '进入专区',
      badge: 'Hot',
    },
  ],
  categories: [
    { id: 'all', name: '全部', filterKey: 'all', target: 'productSection' },
    { id: 'portrait', name: '人像肤色', filterKey: 'portrait_grade', target: 'productSection' },
    { id: 'commercial', name: '商业广告', filterKey: 'commercial_grade', target: 'productSection' },
    { id: 'film', name: '胶片仿真', filterKey: 'film_emulation', target: 'productSection' },
    { id: 'documentary', name: '纪实纪录', filterKey: 'documentary_grade', target: 'productSection' },
    { id: 'davinci', name: '节点工程', filterKey: 'davinci_nodes', target: 'productSection' },
    { id: 'workflow', name: '交付流程', filterKey: 'delivery_workflow', target: 'productSection' },
  ],
  inspirations: [
    {
      id: 'inspire_001',
      title: '商业暖肤案例墙',
      subtitle: '把参考帧、对比曲线和最终输出放到一个板上',
      badge: 'Case Study',
      cover: IMAGE_SET.inspireCase,
    },
    {
      id: 'inspire_002',
      title: '品牌调性配色库',
      subtitle: '适合客户提案和前期 moodboard 建立',
      badge: 'Palette',
      cover: IMAGE_SET.inspirePalette,
    },
    {
      id: 'inspire_003',
      title: 'ACES 节点拆解',
      subtitle: '从主校正到局部修饰的结构化思路',
      badge: 'Workflow',
      cover: IMAGE_SET.inspireWorkflow,
    },
    {
      id: 'inspire_004',
      title: '参考帧精选',
      subtitle: '适合人像、广告、纪录片的风格参考集合',
      badge: 'Reference',
      cover: IMAGE_SET.inspireReference,
    },
  ],
  creators: [
    {
      id: 'creator_001',
      name: '林屿',
      role: '品牌广告调色师',
      score: 'Top 01',
      metric: '服务品牌 60+',
      avatar: createAvatar('LY'),
    },
    {
      id: 'creator_002',
      name: '言川',
      role: '剧情短片色彩顾问',
      score: 'Top 02',
      metric: '短片交付 120+',
      avatar: createAvatar('YC', 'E8DDD2', '71503F'),
    },
    {
      id: 'creator_003',
      name: '周澄',
      role: '纪录片后期流程设计',
      score: 'Top 03',
      metric: '流程模板 18 套',
      avatar: createAvatar('ZC', 'EFE4D9', '6A4E3E'),
    },
    {
      id: 'creator_004',
      name: '纪和',
      role: 'DaVinci 节点工程师',
      score: 'Top 04',
      metric: '节点库 40+',
      avatar: createAvatar('JH', 'F2E8DE', '7A5A45'),
    },
  ],
  products: [
    {
      id: 'product_001',
      title: '人像肤色控制 LUT 套装 Pro',
      description: '针对高端写真、婚礼跟拍和人物专访的肤色提纯与环境偏色控制方案。',
      price: 169,
      sales: 1268,
      cover: PRODUCT_IMAGES.portraitPro[0],
      tags: ['LUT 套装', '肤色控制', '人像项目'],
      gallery: PRODUCT_IMAGES.portraitPro,
      detailContent: [
        '这套资源以真实交付中的肤色稳定性为核心，覆盖室内暖光、自然逆光、夜景混合光等高频场景。',
        '它不是只追求“白”和“亮”，而是帮助你更稳定地控制肤色层次、灰度过渡与面部立体感。',
        '适合高客单写真馆、独立摄影师和对成片气质要求较高的人像视频项目。',
      ],
      deliverables: ['18 组肤色控制 LUT', '6 套匹配节点预设', '项目应用建议 PDF'],
      usageNotice: ['建议先统一白平衡与曝光', '夜景混光素材请先做局部偏色校正后再套用'],
      isNew: true,
      isHot: true,
      category: 'portrait_grade',
    },
    {
      id: 'product_002',
      title: '婚礼纪实柔光调色包',
      description: '面向婚礼快剪与纪实长片的柔和高光、奶油肤色与情绪氛围方案。',
      price: 139,
      sales: 978,
      cover: PRODUCT_IMAGES.weddingSoft[0],
      tags: ['LUT 套装', '婚礼纪实', '柔光风格'],
      gallery: PRODUCT_IMAGES.weddingSoft,
      detailContent: [
        '针对婚礼纪实常见的逆光、酒店暖光、追焦移动镜头做了更友好的层次保留。',
        '整体风格偏柔和、克制、不发灰，能兼顾情绪片和交付效率。',
        '尤其适合需要当天快剪、次日交片的婚礼团队和独立拍摄工作室。',
      ],
      deliverables: ['12 组婚礼风格 LUT', '婚礼快剪流程卡', '前后对比图示例'],
      usageNotice: ['建议搭配轻微胶片颗粒使用', '室内深黄光素材建议降低色温后再使用'],
      isNew: false,
      isHot: true,
      category: 'portrait_grade',
    },
    {
      id: 'product_003',
      title: '轻奢商业广告主视觉包',
      description: '为化妆品、珠宝、家居和服饰类品牌短片准备的高质感商业方案。',
      price: 219,
      sales: 1560,
      cover: PRODUCT_IMAGES.adLux[0],
      tags: ['PowerGrade', '商业广告', '高光控制'],
      gallery: PRODUCT_IMAGES.adLux,
      detailContent: [
        '这是一套偏“品牌成片”的商业调色资源，重点处理产品高光、背景干净度和整体质感统一。',
        '适合广告片、品牌短视频、KV 预演样片和提案阶段的风格建立。',
        '相比普通 LUT，它更强调层次保留与细节整理，适合反复复用在商业项目中。',
      ],
      deliverables: ['完整 PowerGrade 工程', '广告片分层节点模板', '客户预览输出建议'],
      usageNotice: ['建议在 DaVinci Resolve 中使用以获得最佳节点结构体验', '高反差素材请先做高光压缩'],
      isNew: true,
      isHot: true,
      category: 'commercial_grade',
    },
    {
      id: 'product_004',
      title: '美食与餐饮短视频调色模板',
      description: '提升食物饱满度、灯箱通透感和暖色食欲氛围的商业短视频资源。',
      price: 129,
      sales: 1104,
      cover: PRODUCT_IMAGES.foodAd[0],
      tags: ['LUT 套装', '餐饮短视频', '商业暖调'],
      gallery: PRODUCT_IMAGES.foodAd,
      detailContent: [
        '围绕食物色泽、蒸汽氛围、木质桌面与暖色环境光进行专项优化。',
        '能帮助连锁餐饮、探店博主和本地生活短视频提升出片效率。',
        '整体色调偏温暖、饱满、不过分艳俗，适合稳定复用。',
      ],
      deliverables: ['10 组餐饮风格 LUT', '食物高光微调节点', '短视频导出建议'],
      usageNotice: ['红色食材请注意饱和度上限', '暖色灯箱素材建议降低红通道后再套用'],
      isNew: false,
      isHot: true,
      category: 'commercial_grade',
    },
    {
      id: 'product_005',
      title: '胶片尘埃电影感 LUT Collection',
      description: '适合剧情短片、访谈和氛围片的胶片质感、暗部密度与柔和高光方案。',
      price: 189,
      sales: 888,
      cover: PRODUCT_IMAGES.filmDust[0],
      tags: ['LUT 套装', '胶片仿真', '剧情短片'],
      gallery: PRODUCT_IMAGES.filmDust,
      detailContent: [
        '重点模拟胶片暗部密度、轻微色偏和更自然的高光 roll-off。',
        '不是极端复古滤镜，而是更偏“现代胶片感”的稳定落地方案。',
        '适合剧情短片、人物访谈、音乐短片和品牌故事内容。',
      ],
      deliverables: ['16 组胶片风格 LUT', '颗粒叠加建议', '镜头前后对比参考'],
      usageNotice: ['建议配合适度颗粒和轻锐化使用', '阴天低对比素材建议先抬中灰再套用'],
      isNew: true,
      isHot: true,
      category: 'film_emulation',
    },
    {
      id: 'product_006',
      title: '独立短片低饱和风格预设',
      description: '适用于 A24 风格、人文题材和低饱和叙事影像的统一色彩方案。',
      price: 149,
      sales: 624,
      cover: PRODUCT_IMAGES.indieMuted[0],
      tags: ['PowerGrade', '低饱和', '独立短片'],
      gallery: PRODUCT_IMAGES.indieMuted,
      detailContent: [
        '以低饱和、克制反差和柔化色块作为主要方向，适合氛围叙事型项目。',
        '资源内置多组微调节点，可以快速切换成更冷静或更暖意的人文风格。',
        '适合作者短片、纪录访谈、艺术院校毕业作品等项目使用。',
      ],
      deliverables: ['8 套低饱和 PowerGrade', '冷暖双向微调方案', '导演提案参考图'],
      usageNotice: ['建议保留皮肤微量暖色避免过灰', '高彩度服装素材需压一下局部饱和度'],
      isNew: false,
      isHot: false,
      category: 'film_emulation',
    },
    {
      id: 'product_007',
      title: '纪录片自然校正基础包',
      description: '面向采访、街拍和纪实类项目的自然校正、肤色统一与快速交付方案。',
      price: 119,
      sales: 1436,
      cover: PRODUCT_IMAGES.docNatural[0],
      tags: ['LUT 套装', '纪录片', '自然校正'],
      gallery: PRODUCT_IMAGES.docNatural,
      detailContent: [
        '强调“自然、不突兀、稳定”的交付逻辑，适合需要大量素材统一的纪录片项目。',
        '帮助你快速完成白平衡统一、肤色压偏和对比校正，减少逐镜试错。',
        '适合纪录片团队、品牌纪实、口播访谈和课程录制内容。',
      ],
      deliverables: ['14 组自然校正 LUT', '采访布光建议', '批量套用说明'],
      usageNotice: ['不建议用于强风格片头主视觉', '多机位拍摄建议先做机内色彩匹配'],
      isNew: false,
      isHot: true,
      category: 'documentary_grade',
    },
    {
      id: 'product_008',
      title: '新闻快剪统一风格包',
      description: '适合高频更新、低返工需求的资讯短片与机构宣传内容调色资源。',
      price: 99,
      sales: 1710,
      cover: PRODUCT_IMAGES.newsFast[0],
      tags: ['LUT 套装', '快剪交付', '统一风格'],
      gallery: PRODUCT_IMAGES.newsFast,
      detailContent: [
        '为时间敏感的资讯短片设计，尽量减少复杂节点，强调上手快、容错高。',
        '在保持画面干净的同时，让整组内容保持相对统一的色彩呈现。',
        '适合机构宣传、活动快剪、企业内宣、校园媒体与资讯栏目。',
      ],
      deliverables: ['9 组快剪 LUT', '交付命名规范', '导出参数建议'],
      usageNotice: ['建议作为基础统一层，不必过度叠加强风格节点', '肤色微偏时请先做一级色彩校正'],
      isNew: false,
      isHot: false,
      category: 'documentary_grade',
    },
    {
      id: 'product_009',
      title: 'DaVinci 节点工程母版',
      description: '把一级校正、二级修饰、肤色、氛围与导出节点规范化的工程模板。',
      price: 249,
      sales: 742,
      cover: PRODUCT_IMAGES.nodeMaster[0],
      tags: ['PowerGrade', 'DaVinci', '节点工程'],
      gallery: PRODUCT_IMAGES.nodeMaster,
      detailContent: [
        '如果你已经在接真实商业项目，这套工程模板会明显提升你的项目组织效率。',
        '它不是单一风格资产，而是一套更适合长期复用的节点结构母版。',
        '从主校正、局部修饰、风格层到导出前检查，都做了较完整的分层规范。',
      ],
      deliverables: ['母版工程文件', '节点命名规范', '项目交接说明模板'],
      usageNotice: ['建议在 DaVinci Resolve 18+ 使用', '首次接入时请按你的项目命名习惯调整分组结构'],
      isNew: true,
      isHot: true,
      category: 'davinci_nodes',
    },
    {
      id: 'product_010',
      title: '客户交付流程清单包',
      description: '从接单、提案、调色、审片到最终交付的个人工作室标准化模板集合。',
      price: 159,
      sales: 538,
      cover: PRODUCT_IMAGES.deliveryPack[0],
      tags: ['流程模板', '客户交付', '标准化'],
      gallery: PRODUCT_IMAGES.deliveryPack,
      detailContent: [
        '适合个人调色师、两三人后期团队和工作室把项目流程逐步标准化。',
        '内容覆盖报价沟通、项目接收、版本管理、审片反馈和最终交付结构。',
        '如果你已经有稳定客源，这套模板会比单纯买 LUT 更能提升专业感和效率。',
      ],
      deliverables: ['交付流程清单', '客户沟通模板', '项目文件夹结构建议'],
      usageNotice: ['更偏管理与协作，不是视觉风格预设', '建议结合你自己的报价流程再做二次修改'],
      isNew: true,
      isHot: false,
      category: 'delivery_workflow',
    },
  ],
  articles: [
    {
      id: 'article_001',
      title: 'HDR 监看环境怎么搭，个人工作室最少要准备什么',
      cover: IMAGE_SET.articleMonitor,
      views: 12640,
      author: '艺匠调色',
      publishTime: '2026-05-10',
    },
    {
      id: 'article_002',
      title: '人像肤色总是飘？这 5 个判断点要固定下来',
      cover: IMAGE_SET.articleSkin,
      views: 9840,
      author: '林屿',
      publishTime: '2026-05-06',
    },
    {
      id: 'article_003',
      title: 'DaVinci 节点命名和分层，为什么越早规范越省心',
      cover: IMAGE_SET.articleWorkflow,
      views: 8630,
      author: '纪和',
      publishTime: '2026-04-28',
    },
    {
      id: 'article_004',
      title: '给客户交付时，文件结构和版本备注该怎么写',
      cover: IMAGE_SET.articleDelivery,
      views: 7420,
      author: '周澄',
      publishTime: '2026-04-19',
    },
  ],
};
