export const HOME_MOCK = {
  app: {
    name: 'CineGrade',
    slogan: 'Professional Color Grading Assets',
    version: '2.1.0',
  },
  metrics: [
    { id: 'metric_001', value: '1.2k+', label: '调色资产' },
    { id: 'metric_002', value: '98%', label: '高评分推荐' },
    { id: 'metric_003', value: '24h', label: '持续上新' },
  ],
  banners: [
    {
      id: 'banner_001',
      title: 'Blade Runner LUT Collection',
      subtitle: 'Cyberpunk cinematic grading toolkit',
      description: '为暗色、霓虹与高对比画面准备的电影级 LUT 套件。',
      image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4',
      buttonText: '立即查看',
      badge: 'NEW',
    },
    {
      id: 'banner_002',
      title: 'Hollywood HDR Masterclass',
      subtitle: 'ACES + Dolby Vision Workflow',
      description: '把 HDR 流程、色彩空间和交付规范串成可落地工作流。',
      image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32',
      buttonText: '开始学习',
      badge: 'HOT',
    },
    {
      id: 'banner_003',
      title: 'AI Color Matching Engine',
      subtitle: 'Train your own cinematic look',
      description: '借助 AI 参考匹配，快速建立统一、克制、专业的电影风格。',
      image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728',
      buttonText: '体验 AI',
      badge: 'AI',
    },
  ],
  categories: [
    { id: 'all', name: '精选推荐', filterKey: 'all', target: 'productSection' },
    { id: 'HDR', name: 'HDR', filterKey: 'HDR', target: 'productSection' },
    { id: 'LUT', name: 'LUT', filterKey: 'LUT', target: 'productSection' },
    { id: 'ACES', name: 'ACES', filterKey: 'ACES', target: 'productSection' },
    { id: 'AI', name: 'AI', filterKey: 'AI', target: 'productSection' },
    { id: 'article', name: '文章', filterKey: 'all', target: 'articleSection' },
    { id: 'plugin', name: '插件', filterKey: 'all', target: 'inspirationSection' },
    { id: 'course', name: '课程', filterKey: 'all', target: 'articleSection' },
    { id: 'film', name: '电影胶片', filterKey: '胶片', target: 'productSection' },
    { id: 'powergrade', name: 'PowerGrade', filterKey: 'all', target: 'productSection' },
  ],
  inspirations: [
    {
      id: 'inspire_001',
      title: '今日灵感',
      subtitle: '电影截图 · 色彩分析 · LUT 拆解',
      badge: 'Inspiration',
      cover: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4',
    },
    {
      id: 'inspire_002',
      title: '热门电影 LUT',
      subtitle: 'Joker / Dune / The Batman / Mad Max',
      badge: 'Popular',
      cover: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32',
    },
    {
      id: 'inspire_003',
      title: 'AI 调色实验室',
      subtitle: '上传参考片，自动生成电影色调',
      badge: 'AI Lab',
      cover: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
    },
  ],
  products: [
    {
      id: 'product_001',
      title: 'Cinematic Orange Teal LUT Pack',
      description: '电影级橙青调色 LUT，适用于商业广告与短片',
      price: 128,
      originalPrice: 228,
      rating: 4.9,
      sales: 3280,
      favorites: 1209,
      cover: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32',
      author: {
        name: 'Chen Color',
        avatar: 'https://i.pravatar.cc/100?img=1',
      },
      tags: ['LUT', '电影感', '商业广告'],
      isNew: true,
      isHot: true,
      category: 'LUT',
    },
    {
      id: 'product_002',
      title: 'Blade Runner 2049 HDR Workflow',
      description: 'HDR 电影工业级调色流程完整教学',
      price: 108,
      originalPrice: 399,
      rating: 5.0,
      sales: 5690,
      favorites: 2400,
      cover: 'https://images.unsplash.com/photo-1485846234645-a62644f84728',
      author: {
        name: 'HDR Studio',
        avatar: 'https://i.pravatar.cc/100?img=2',
      },
      tags: ['HDR', 'ACES', '达芬奇'],
      isNew: false,
      isHot: true,
      category: 'HDR',
    },
    {
      id: 'product_003',
      title: 'Kodak 2383 Film Emulation',
      description: '还原 Kodak 电影胶片质感',
      price: 88,
      originalPrice: 168,
      rating: 4.8,
      sales: 1932,
      favorites: 886,
      cover: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1',
      author: {
        name: 'FilmConvert Lab',
        avatar: 'https://i.pravatar.cc/100?img=3',
      },
      tags: ['胶片', 'Kodak', 'Film Look'],
      isNew: true,
      isHot: false,
      category: '胶片',
    },
    {
      id: 'product_004',
      title: 'Netflix Approved ACES Pipeline',
      description: 'Netflix 认证影视工业流程',
      price: 299,
      originalPrice: 699,
      rating: 5.0,
      sales: 920,
      favorites: 502,
      cover: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4',
      author: {
        name: 'ACES Academy',
        avatar: 'https://i.pravatar.cc/100?img=4',
      },
      tags: ['ACES', 'Netflix', 'Workflow'],
      isNew: false,
      isHot: true,
      category: 'ACES',
    },
    {
      id: 'product_005',
      title: 'AI Auto Color Match Plugin',
      description: 'AI 智能匹配电影色彩风格',
      price: 168,
      originalPrice: 299,
      rating: 4.7,
      sales: 2010,
      favorites: 1400,
      cover: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
      author: {
        name: 'NeuralGrade',
        avatar: 'https://i.pravatar.cc/100?img=5',
      },
      tags: ['AI', 'Plugin', 'DaVinci'],
      isNew: true,
      isHot: true,
      category: 'AI',
    },
    {
      id: 'product_006',
      title: 'Commercial Beauty LUT Collection',
      description: '高级美妆广告调色方案',
      price: 148,
      originalPrice: 268,
      rating: 4.9,
      sales: 4200,
      favorites: 2200,
      cover: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
      author: {
        name: 'Beauty Grade',
        avatar: 'https://i.pravatar.cc/100?img=6',
      },
      tags: ['Beauty', 'Commercial', 'LUT'],
      isNew: false,
      isHot: true,
      category: 'LUT',
    },
  ],
  articles: [
    {
      id: 'article_001',
      title: 'HDR 与 SDR 调色核心区别',
      cover: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4',
      views: 9200,
      author: 'Chen Color',
      publishTime: '2026-05-01',
    },
    {
      id: 'article_002',
      title: 'ACES 工作流完整指南',
      cover: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32',
      views: 6800,
      author: 'ACES Academy',
      publishTime: '2026-04-20',
    },
    {
      id: 'article_003',
      title: '如何做出 A24 式低饱和电影感',
      cover: 'https://images.unsplash.com/photo-1485846234645-a62644f84728',
      views: 7520,
      author: 'FilmConvert Lab',
      publishTime: '2026-04-08',
    },
  ],
};
